### ISSUE TITLE
Can i seed the same table multiple times?

### ISSUE THREAD

**Issue by polgarz** [tebazil/db-seeder#10]
Hello!

First of all, thank you for your work! :)

I have a problem. I'd like to insert into the same table multiple times like:

```php
        $seeder->table('offer')->columns([
            'id',
            'type' => 'time',
            'publisher_id',
            'name' => $faker->catchPhrase,
            'name_local' => $faker->catchPhrase,
            'description' => $faker->realText(),
            'description_local' => $faker->realText(),
            'price' => $faker->numberBetween(),
            'min_av' => $faker->optional()->numberBetween(),
            'max_av' => $faker->optional()->numberBetween(),
            'active' => 1,
        ])->rowQuantity(25);

        $seeder->table('offer')->columns([
            'id',
            'type' => 'av',
            'publisher_id',
            'name' => $faker->catchPhrase,
            'name_local' => $faker->catchPhrase,
            'description' => $faker->realText(),
            'description_local' => $faker->realText(),
            'price' => $faker->numberBetween(0, 5000),
            'min_av' => $faker->optional()->numberBetween(0, 100000),
            'active' => 1,
        ])->rowQuantity(25);
```

It's because different type of offer needs different kind of data. 

I get this error:
**Something unexpected happened: some tables possibly cannot be filled**

Can somebody help me figure it out? :)

Thanks in advance!

**Comment by vambus** [comment]
Yes, I think we should be able to fill the table again. That could probably be archieved by resetting the internal data associated with the table, if there as an attempt to fill it again.
I will try to fix that.
Thanks for bringing this issue up!

**Comment by vambus** [comment]
Sorry, this is not easy to implement design-wise, and it does not seem to be a popular feature. 
As I understand it, you will be able to archieve the result with something like:

```php
$fakerReal = \Faker\Factory::create(); //somewhere on top
...
'price' => function() use($fakerReal) { 
  static $counter=0;
  $counter++;
  return $counter > 30 ? $fakerReal->numberBetween(0, 5000) : $fakerReal->numberBetween(); 
}
```

Let me know if you have any questions. Sorry it took more than a year to answer.
