### ISSUE TITLE
Missing support for valid()

### ISSUE THREAD

**Issue by olleharstedt** [tebazil/db-seeder#13]
You added optional and unique but not valid, for some reason. :)

Simple PR, if you would accept it.

**Comment by vambus** [comment]
Thanks for pointing it out, Olle! Do you think you have time and... willingness to make a PR?

**Comment by olleharstedt** [comment]
I already did the change locally to test it, so yes, no problem to make a PR.

**Comment by vambus** [comment]
Thanks, Olle!
