### ISSUE TITLE
Don't insert into table

### ISSUE THREAD

**Issue by ghost** [tebazil/db-seeder#3]
``` php
class FakerController extends Controller {

    public function actionFaker() {
        $pdo = new \PDO('mysql:localhost;dbname=mafia-yii', 'mafia-yii', 'cantsay');
        $seeder = new \tebazil\dbseeder\Seeder($pdo);
        $generator = $seeder->getGeneratorConfigurator();
        $faker = $generator->getFakerConfigurator();

        $seeder->table('user')->columns([
            'username' => $faker->userName,
            'email' => $faker->email,
            'realName' => $faker->firstName,
            'lastName' => $faker->lastName,
            'sex' => $faker->randomElement($array = array ('Woman','Man','Other gender')),
            'birthDate' => $faker->date($format = 'Y-m-d', $max = '-12 years'),
            'country' => $faker->country,
            'area' => $faker->state,
            'city' => $faker->city,
            'password' => Yii::$app->getSecurity()->generatePasswordHash('mDK#x9MX%P4r8#P'),
            'secret_question' => 'Your mother maiden name?',
            'secret_question_answer' => Yii::$app->getSecurity()->generatePasswordHash('Blank'),
            'auth_key' => Yii::$app->getSecurity()->generateRandomString(),
            'status' => 10,
        ])->rowQuantity(30);

        $seeder->refill();
    }
}
```

**renders:**

Executing "TRUNCATE TABLE user" >>> Executing "INSERT INTO user(username, email, realName, lastName, sex, birthDate, country, area, city, password, secret_question, secret_question_answer, auth_key, status) VALUES (:username, :email, :realName, :lastName, :sex, :birthDate, :country, :area, :city, :password, :secret_question, :secret_question_answer, :auth_key, :status)" with params: (:username => maximo.little, :email => ibosco@legros.com, :realName => Dortha, :lastName => Rempel, :sex => Other gender, :birthDate => 1974-04-18, :country => French Guiana, :area => Nevada, :city => Corenebury, :password => $2y$13$igPNashDFAsEIVtOzp5T6uMHvkCveee52z06E6HrpWzkBsTrL8F66, :secret_question => Your mother maiden name?, :secret_question_answer => $2y$13$JyJyPkz2PgIH3V8idobF5OU8XUq/xHmReSA46GzBaCeIVQRaC5k7S, :auth_key => V4Q8gKRwoGmYTIlkPYoYKiHqD4rgRSI_, :status => 10) >>> Executing "INSERT INTO user(username, email, realName, lastName, sex, birthDate, country, area, city, password, secret_question, secret_question_answer, auth_key, status) VALUES (:username, :email, :realName, :lastName, :sex, :birthDate, :country, :area, :city, :password, :secret_question, :secret_question_answer, :auth_key, :status)" with params: (:username => gregorio14, :email => daugherty.demario@hotmail.com, :realName => Everett, :lastName => Stracke, :sex => Man, :birthDate => 1983-08-11, :country => Puerto Rico, :area => New Mexico, :city => Jarretfort, :password => $2y$13$igPNashDFAsEIVtOzp5T6uMHvkCveee52z06E6HrpWzkBsTrL8F66, :secret_question => Your mother maiden name?, :secret_question_answer => $2y$13$JyJyPkz2PgIH3V8idobF5OU8XUq/xHmReSA46GzBaCeIVQRaC5k7S, :auth_key => V4Q8gKRwoGmYTIlkPYoYKiHqD4rgRSI_, :status => 10) >>>
.....**and so on**

but nothing inserted in database

**Comment by vambus** [comment]
@rumatakira you have a typo.
It should be 

``` php
$pdo = new \PDO('mysql:host=localhost;dbname=mafia-yii', 'mafia-yii', 'cantsay');
```

instead of

``` php
$pdo = new \PDO('mysql:localhost;dbname=mafia-yii', 'mafia-yii', 'cantsay');
```

**Comment by ghost** [comment]
Sorry!

**Comment by paskuale75** [comment]
For me work only if I wrote databaseName.TableName format

$seeder->table('yii2_my_db.table_personale')->columns([.....
