### ISSUE TITLE
Something went wrong... PHP Fatal error:  Uncaught Error: Class 'tebazil\dbseeder\Seeder' not found in /home/work

### ISSUE THREAD

**Issue by levaconline** [tebazil/db-seeder#6]
Folliwing line generates error:
`$seeder = new \tebazil\dbseeder\Seeder($this->con);
`

> PHP Fatal error:  Uncaught Error: Class 'tebazil\dbseeder\Seeder' not found in /home/work...

Composer put db-seeder under: vendor/tebazil/db-seeder/src/Seeder.php

--------------------------------------------------------------------------------------------------------
php -v
PHP 7.2.6 (cli) (built: May 26 2018 07:45:18) ( NTS )
--------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
Using version ^1.7 for fzaninotto/faker
--------------------------------------------------------------------------------------------------------

**Comment by vambus** [comment]
Please make sure you have
`require_once "vendor/autoload.php";`
run somewhere so that composer autoload is working.

**Comment by levaconline** [comment]
This helped. Thanx!
