### ISSUE TITLE
Inserting Same Rows  or Add providers in Faker Wrapper

### ISSUE THREAD

**Issue by mushahidh** [tebazil/db-seeder#7]
I have created a seeder for my db. The problem I am getting is that when I use `$faker = $generator->getFakerConfigurator(); ` Instance I am able to add providers in it like book provider etc but in that case, the seeder generates same data for each row. Likewise, when I use the faker wrapper it does not allow me to add any faker provider however, It does generate the unique data for each row. Can you tell me how to add faker providers with db-seeder faker wrapper? or generate unique data with original faker instance.
Thanks in advance.

**Comment by vambus** [comment]
Good day, @mushahidh !

Please help me understand the question. Is it true that code like 

```php
$faker = $generator->getFakerConfigurator();

$seeder->table('article')->columns([
    'id', //automatic pk
    'book_id', //automatic fk
    'name'=>$faker->firstName,
    'content'=>$faker->text
        ])->rowQuantity(30);
```

Generates the same content for each of the 30 rows for you?

**Comment by vambus** [comment]
Here is a (didn't check the code) concept to use real faker in generators:
```php $fakerReal = \Faker\Factory::create(); //somewhere on top
...
'price' => function() use($fakerReal) { 
  return $fakerReal->numberBetween(0, 5000); 
}
```
